### ISSUE TITLE
Failure to Start - Versions Beyond 1.7.6.7

### ISSUE THREAD

**Issue by xLinkKnight** [Rappsilber-Laboratory/XiSearch#109]
Crosslink searches fail to start when using xiSERACH versions 1.8.3 and 1.8.4.1.

Pressing start results in no action. No entry is displayed in the log file. Using version 1.7.6.7 with all the same search parameters works as intended.

**Comment by Rafiei297** [comment]
I have same issue with version 1.8.4.1

**Comment by grandrea** [comment]
Thanks for the report- what OS? Are you launching by clicking directly on the java icon or by using the launch script? I am running 1.8.3 on windows and it does work for me...

**Comment by xLinkKnight** [comment]
The OS is Windows 11 and xiSEARCH is place in the root C:\ directory. I was directly clicking on the xiSEARCH jar file. I didn't use the bat file due to the 1.8.X.X updates incorporating the RAM utilization natively in the xiSEARCH GUI. (We added the -Xmx flag to increase memory usage.)

I can try using the launch script when I get a chance. Thank you.

**Comment by lutzfischer** [comment]
what java version are you using?

**Comment by lutzfischer** [comment]
Could you try the version from https://tubcloud.tu-berlin.de/s/jLtp5dWGdJc5m9W

It has two changes related to java directly
* (hopefully) improved detection of the used java version 
* improved detection of the used java executable

The first one I have just seen an error - and the second one is to make a bi t more tolerant towards "odd"  java setups.

**Comment by lutzfischer** [comment]
if you run from the startWindows.bat can you copy what ever is written in the terminal/command/black window. it might hold a  clue on what is going on

**Comment by helloworld1631** [comment]
Hi, I click the startWindows.bat to open xiSEARCH GUI window. After setting all parameters, it failed to start searching with an error saying: 
"Jul 17, 2024 3:51:27 PM rappsilber.gui.components.CallBackSettings$2 run
INFO: latest online version: 1.8.4
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.alignedSlice(I)Ljava/nio/ByteBuffer;
        at rappsilber.ui.MemMapStatusControl.<init>(MemMapStatusControl.java:54)
        at rappsilber.gui.SimpleXiGui.innerStartXiSEARCH(SimpleXiGui.java:954)
        at rappsilber.gui.SimpleXiGui.startXiProcess(SimpleXiGui.java:888)
        at rappsilber.gui.SimpleXiGui.btnStartSearch2btnStartSearchActionPerformed(SimpleXiGui.java:2281)
        at rappsilber.gui.SimpleXiGui.access$6700(SimpleXiGui.java:104)
        at rappsilber.gui.SimpleXiGui$44.actionPerformed(SimpleXiGui.java:1962)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)"

It looks like there is an issue with Java version

**Comment by helloworld1631** [comment]
Tried the xiSEARCH 1.8.5 but the problem still exists. 
My Windows OS is 22631.3593. And my java version 1.8.0_421 .

**Comment by xLinkKnight** [comment]
Our Java installation is standard. Running Java 8 (build 1.8.0_411-b09). I'll try hotfix 1.8.5 when our system is free.

**Comment by xLinkKnight** [comment]
I receive the following when using the 1.8.5 files in place of the 1.8.4.1 .jar files. I've ensured the .conf and template files are present.

```!!!reading config!!!
from : .rappsilber.data.DefaultConfig.conf
java.lang.NullPointerException
Jul 17, 2024 3:44:04 PM rappsilber.gui.SimpleXiGui <init>
INFO: Logger Connected
Jul 17, 2024 3:44:05 PM rappsilber.gui.components.CallBackSettings$2 run
INFO: Checking for new Version with: https://rappsilberlab.org/xiversion/check.php?user=ab2747d4-7c35-4595-ab59-cea5a715db3b
Jul 17, 2024 3:44:06 PM rappsilber.gui.components.CallBackSettings$2 run
INFO: Response:1.8.4

Jul 17, 2024 3:44:06 PM rappsilber.gui.components.CallBackSettings$2 run
INFO: latest online version: 1.8.4
```

**Comment by lutzfischer** [comment]
can you try with a newer version of java? I think some of the stuff i did to define the memory in the gui is only available in java 9 and up. will see if I can find a solution that works with 8.

**Comment by xLinkKnight** [comment]
Using Java 9 (JDK 22) fixed the issue. Searches now progress. 

Thanks for the support.
