### ISSUE TITLE
Error Loading Results into xiFDR

### ISSUE THREAD

**Issue by xLinkKnight** [Rappsilber-Laboratory/XiSearch#113]
xiSEARCH version 1.8.4.1.
xiFDR version 2.2.4.

After the xiSEARCH completes, reading the results into xiFDR produces the following error:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "org.rappsilber.fdr.OfflineFDR.stubsFound()" because "this.val$cfdr" is null
	at org.rappsilber.fdr.gui.FDRGUI$9.run(FDRGUI.java:493)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:881)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:677)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:648)
	at org.rappsilber.fdr.gui.FDRGUI$5$3.run(FDRGUI.java:293)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:881)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:677)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:648)
	at org.rappsilber.fdr.gui.FDRGUI$5$3.run(FDRGUI.java:295)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Displayed error in xiFDR log:
```
Aug 10, 2024 8:01:47 PM org.rappsilber.data.csv.CsvParser setCurrentLine
WARNING: line 2 contains more fields than ever observed!
"20240729_BLVRB_Cyt_Xlink_Frac1",4356,"20240729_BLVRB_Cyt_Xlink_Frac1.4356.4356.2 File: 20240729_BLVRB_Cyt_Xlink_Frac1.raw , NativeID: controllerType=0 controllerNumber=1 scan=4356 ","20240729_BLVRB_Cyt_Xlink_Frac1.mgf",126,"null -> F:\Data\PERSON\20240729_BLVRB_Cyt_Xlink\MGFs\20240729_BLVRB_Cyt_Xlink_Frac1.mgf->F:\Data\PERSON\20240729_BLVRB_Cyt_Xlink\MGFs\20240729_BLVRB_Cyt_Xlink_Frac1.mgf",1275.332676,-1,806.447913,2,404.231233,1030179.73349,806.439882,404.227218,false,1,1,"EDC",-18.01056,0,"REV_P34820-2","REV_BMP8B_HUMAN","BMP8B_HUMAN Isoform 2 of Bone morphogenetic protein 8B OS=Homo sapiens OX=9606 GN=BMP8B","sp|REV_P34820-2|REV_REV_BMP8B_HUMAN Isoform 2 of Bone morphogenetic protein 8B OS=Homo sapiens OX=9606 GN=REV_BMP8B",1,"E.DGGR.A","DGGR","D(1.00)GGR",403.181542,0,158,4,1,"D","LRKHLLWDCSAATDVLVLWEDGGRALTQDLLFFDLERSNSE",158,1,1,,,,,,,"REV_P02549-2;REV_P02549-2;REV_P11277-2;REV_Q00975-2","REV_SPTA1_HUMAN;REV_SPTA1_HUMAN;REV_SPTB1_HUMAN;REV_CAC1B_HUMAN","SPTA1_HUMAN Isoform 2 of Spectrin alpha chain, erythrocytic 1 OS=Homo sapiens OX=9606 GN=SPTA1;SPTA1_HUMAN Isoform 2 of Spectrin alpha chain, erythrocytic 1 OS=Homo sapiens OX=9606 GN=SPTA1;SPTB1_HUMAN Isoform 2 of Spectrin beta chain, erythrocytic OS=Homo sapiens OX=9606 GN=SPTB;CAC1B_HUMAN Isoform Alpha-1B-2 of Voltage-dependent N-type calcium channel subunit alpha-1B OS=Homo sapiens OX=9606 GN=CACNA1B","sp|REV_P02549-2|REV_REV_SPTA1_HUMAN Isoform 2 of Spectrin alpha chain, erythrocytic 1 OS=Homo sapiens OX=9606 GN=REV_SPTA1;sp|REV_P02549-2|REV_REV_SPTA1_HUMAN Isoform 2 of Spectrin alpha chain, erythrocytic 1 OS=Homo sapiens OX=9606 GN=REV_SPTA1;sp|REV_P11277-2|REV_REV_SPTB1_HUMAN Isoform 2 of Spectrin beta chain, erythrocytic OS=Homo sapiens OX=9606 GN=REV_SPTB;sp|REV_Q00975-2|REV_CAC1B_HUMAN Isoform Alpha-1B-2 of Voltage-dependent N-type calcium channel subunit alpha-1B OS=Homo sapiens OX=9606 GN=REV_CACNA1B",1,"[DEK].KKF.[FHY]","FKK","K(0.50)K(0.50)F",421.2689,0,"1296;2216;1543;893",3,2,"K","KVNDRIRLEPNTNDKLQEDFKKFQELWDDVELVGTENKKEA","1297;2217;1544;894",3,4,"F->K ;K->K ;K->F ",1;2;3,-18.973450999999983;0.0;18.973450999999983,,,,253,253,3,0.333333,5,1,9.882822,-10.137056,0,9.882822,-0,NaN,NaN,19.058663,0,0.000643,0,0.357263,0,0,0,0,9.932915,9.932915,0.496641,0.503359,4.354517,18.993074,4.358104,0.217726,0.782274,4.531306,4.177728,9999999,-0.176789,0,0,0,0,2,1,3,0.3,2,0.2,1,0.1,2,0.2,2,2,0.2,0,0,2,2,0,0,0,0,0,0,0,0.2,0,NaN,0,0,0,0,1,0,1,0.166667,1,0.166667,0,0,1,0.166667,1,1,0.166667,0,0,1,0.166667,1,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,2,0.5,1,0.25,1,0.25,1,0.25,1,1,0.25,1,0.25,1,0.25,1,0,0,0,0,0,0,0,0,NaN,0,0,0,0,1,1,Infinity,0.138668,0.138668,0,0,0.138668,0.2,0.1,0.05,0.02,0.181818,0.138668,-0,-0,-0,-0,0.153846,0.326923,0.069334,0.19643,0.19643,0.149941,0.206567,0,0,0,0.713882
Aug 10, 2024 8:01:47 PM org.rappsilber.fdr.CSVinFDR readCSV
SEVERE: Unexecpted exception while parsing line 1
java.lang.NumberFormatException: Unparseable number: ""[DEK].KKF.[FHY]""
	at org.rappsilber.data.csv.CsvParser.getInteger(CsvParser.java:1006)
	at org.rappsilber.fdr.CSVinFDR.readCSV(CSVinFDR.java:357)
	at org.rappsilber.fdr.XiCSVinFDR.readCSV(XiCSVinFDR.java:579)
	at org.rappsilber.fdr.gui.FDRGUI.addCSV(FDRGUI.java:1019)
	at org.rappsilber.fdr.gui.FDRGUI.innerBatchReadCSV(FDRGUI.java:890)
	at org.rappsilber.fdr.gui.FDRGUI$12.run(FDRGUI.java:947)
	at java.base/java.lang.Thread.run(Thread.java:1570)

Aug 10, 2024 8:01:47 PM org.rappsilber.fdr.gui.FDRGUI addCSV
```

The exception occurs even when I attempt to used a xiFDR version 2.3 and 2.1.5.5.

**Comment by grandrea** [comment]
I think the error could be due to parsing the quote for text. Could you manually load your xisearch .csv result into the latest version of xiFDR, select double quote as the text delimiter and then press read? thank you

**Comment by xLinkKnight** [comment]
That was the solution.

I changed the default "Quote" option from ```'``` to ```"```.

I appreciate it.

**Comment by grandrea** [comment]
the new release of xiSEARCH/xiFDR should now fix this automatic detection bug.
