### ISSUE TITLE
Out of memory error issue

### ISSUE THREAD

**Issue by heejongkim** [Rappsilber-Laboratory/XiSearch#19]
Hi,

I'm currently benchmarking the crosslinking protocol and just encountering the out of memory error issue consistently.
Here's the error message:

(Search_46)Spectra Read 600

(Search_4)Spectra Read 700

(Search_6)Spectra Read 800

(Search_23)Spectra Read 900

(Search_3)Spectra Read 1000

(Search_25)Spectra Read 1100

Exception in thread "Search_37" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at rappsilber.ms.lookup.fragments.FragmentTreeSlimedArrayMassSplitBuild.getForMass(FragmentTreeSlimedArrayMassSplitBuild.java:493)
	at rappsilber.ms.lookup.fragments.FragmentTreeSlimedArrayMassSplitBuild.getAlphaCandidates(FragmentTreeSlimedArrayMassSplitBuild.java:96)
	at rappsilber.ms.lookup.fragments.FragmentTreeSlimedArrayMassSplitBuild.getAlphaCandidates(FragmentTreeSlimedArrayMassSplitBuild.java:52)
	at rappsilber.applications.SimpleXiProcessLinearIncluded.process(SimpleXiProcessLinearIncluded.java:286)
	at rappsilber.applications.SimpleXiProcess$SearchRunner.run(SimpleXiProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Search_31" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at rappsilber.utils.ArithmeticScoredOccurence.getLowestNEntries(ArithmeticScoredOccurence.java:312)
	at rappsilber.applications.SimpleXiProcessLinearIncluded.process(SimpleXiProcessLinearIncluded.java:303)
	at rappsilber.applications.SimpleXiProcess$SearchRunner.run(SimpleXiProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)

And I used the entire yeast db from ebi proteome reference.
I allocated 200GB RAM space.

Can you please guide me what I'm doing wrong?

Thanks,
hee jong kim

**Comment by heejongkim** [comment]
Somehow this time, it went down to 3800 (36%) but still, the same problem persists.

Jun 05, 2018 5:32:10 PM rappsilber.ui.LoggingStatus setStatus
INFO: 36% processed (2300) 3971 read of 6232
Jun 05, 2018 5:32:10 PM rappsilber.ui.LoggingStatus setStatus
INFO: 36% processed (2300) 3971 read of 6232
(Search_33)Spectra Read 3900

Exception in thread "Search_27" java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at rappsilber.utils.ArithmeticScoredOccurence.multiply(ArithmeticScoredOccurence.java:59)
	at rappsilber.ms.lookup.fragments.FragmentTreeSlimedArrayMassSplitBuild.getAlphaCandidates(FragmentTreeSlimedArrayMassSplitBuild.java:99)
	at rappsilber.ms.lookup.fragments.FragmentTreeSlimedArrayMassSplitBuild.getAlphaCandidates(FragmentTreeSlimedArrayMassSplitBuild.java:52)
	at rappsilber.applications.SimpleXiProcessLinearIncluded.process(SimpleXiProcessLinearIncluded.java:286)
	at rappsilber.applications.SimpleXiProcess$SearchRunner.run(SimpleXiProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)

Thanks,
hee jong kim

**Comment by lutzfischer** [comment]
As it is an  outofmemoryerror I think I need some more info on what your doing. 
How do you start xiSearch?
Can I have the config?
How many proteins do you search?
How many processors does the computer have your running on.
How much memory does it have?

**Comment by heejongkim** [comment]
Hi, 
Here are the answers to your questions.

How do you start xiSearch?

I just used the provided shell script with minor modification. 4G to 200G

Can I have the config?

I used the default config since I used BS3 crosslinker.

How many proteins do you search?

The entire yeast DB from EBI reference proteome was used.

How many processors does the computer have your running on.

48 threads and XiSearch fully utilizes it.

How much memory does it have?

~250GB

Thanks!

**Comment by lutzfischer** [comment]
Xi has a fixed memory requirement that is purly bassed on the size of the search database  (fasta+modifications+missedcleavages). And additionally it also has a per thread memory requirement that is in part also dependent on the search database.
You can reduce the search database quite dramatically (and increase the search-speed) by reducing missed cleavages from 4 to 2 or 1.

Additionally you can reduce the per thread needed amount of memory by adding following option
maxpeakcandidates:10000
This will affect to some extend how candidates for a spectrum are generated. But as long as you don't reduce it massively it should have a small impact on the final result.

Together the memory consumption should be reduced enough to run with a lot less then 200GB.

As the search fails with the outofmemoryerror when it is actually searching spectra and not in the initial phase of setting up the search you could address the problem also by reducing the number of threads by changing:
useCPUs:-2
to e.g.
useCPUs:20

**Comment by heejongkim** [comment]
Thank you for the suggestions.
I'm running it right now but it seems quite slower than I expected.
Out of curiosity, is it possible to run XiSearch across the cluster nodes through SGE?
If that's possible, it would be great!

**Comment by lutzfischer** [comment]
Not sure what speed it runs at and what you expect - so can't really say anything to that at the moment. But you could play with the
topmgxhits:x
setting.
If you put this to e.g. 5 it should speed up the search. But will affect your result somewhat.

Also can you add the setting 
FRAGMENTTREE:FU
This should reduce he memory footprint quite a bit (and possibly make it a bit faster as well).


As for running it on a cluster it is possible by splitting your peak-file and running xi in the command-line version. 
This requires that each node of the cluster has enough resources to run a independent search - but most clusters have fewer CPUs per node so the requirement is a lot smaller. If you look at the output of xi - it tells you at some point after fragmenting the peptides how much memory it actually uses at that point. This is then the fixed amount of memory it requires. On top of that comes the memory per thread. In worst case you should have the same memory again per thread but usually it should be below this - according to what I have observed it is more like 1GB per thread. But that does not really fit to your the initial observation...
If your cluster nodes can cope with this then you just have to split your peak-list and assemble your results. We had it running on a cluster ones - the person doing so is currently not available so can't give you more details. But usually we just run it on a single server.

If your cluster has only java 7 (happened here) and you want to use the option FRAGMENTTREE:FU you will need to download the latest fastutil-7.*.jar from http://fastutil.di.unimi.it/ (http://fastutil.di.unimi.it/fastutil-7.2.1-bin.tar.gz). 
Without this xiSearch should still run on java 7 but was not tested in while.

**Comment by heejongkim** [comment]
Thank you so much for the suggestion.
I will give a shot!
