### ISSUE TITLE
defining diazirine within a peptide ligand

### ISSUE THREAD

**Issue by irahman2** [Rappsilber-Laboratory/XiSearch#32]
I would like to request some assistance on properly setting up the configuration file in XiSearch to identify crosslinked fragments between a purified protein and peptide ligand that contains photoleucine and propragylglycine. I am having trouble trying to define photoleucine as the crosslinker, since there is a net mass loss on the substrate upon crosslinking. Additionally, I am not sure how to define the unnatural amino acids in the FASTA input.

**Comment by lutzfischer** [comment]
best is to define your ligand as
XXXXXLphotoXXXGpropragylXXXX
(what ever the actual sequence is).
In xi you need to define both modifications Lphoto and Gpropragyl at the top of the config (before the cross-linker).
modification:known::SYMBOLEXT:photo;MODIFIED:L;DELTAMASS:11.974848
* 11.97 = N2 -C1 -H4
* known here means that it will neither be used as fixed or variable modification - but only tells xi how to interpret if it find s a Lphoto in the FASTA
Similar for Gpropragyl (what ever that is...)

Then you can define a crosslinker as
crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:diaz;MASS:-28.006148;FIRSTLINKEDAMINOACIDS:Lphoto;SECONDLINKEDAMINOACIDS:*

that means link photo-leucine to anything with the loss of N2 (=-28)

Hope this models what you want to search.

**Comment by lutzfischer** [comment]
hi did this explanation work for you?

**Comment by lutzfischer** [comment]
sorry realised I was somewhat late to see your question - sorry

**Comment by FraenzeMueller** [comment]
Dear Lutz,

I was following your instructions posted here to search my data using photoleucine as crosslinker. It worked quite well, until I reached the FDR calculation. There I got an error while reading in the csv, config and fasta file (in build and standalone FDR). Its maybe because of the fasta file, but I am not sure. Do I have to use the same fasta file as in the search (containing L(photo)), or do I have to switch to the original one for the FDR? 

Error Message:
Feb 07, 2023 9:00:39 AM org.rappsilber.gui.components.JoinedThreadedTextOuput publish
INFO: Start
Feb 07, 2023 9:00:39 AM org.rappsilber.gui.components.JoinedThreadedTextOuput publish
INFO: Read from 20230205_E3_RSLC6_Mueller_MS_TechHub_IMP_XLMS_HEK_photoAA_S1_500ng_DDA_FAIMS_001_test_Xi1.7.6.5.csv
Feb 07, 2023 9:00:39 AM org.rappsilber.fdr.gui.FDRGUI addCSV
INFO: read from V:\User\Fraenze\projekts\photoAA\xiSearch\20230205_E3_RSLC6_Mueller_MS_TechHub_IMP_XLMS_HEK_photoAA_S1_500ng_DDA_FAIMS_001_test_Xi1.7.6.5.csv
Feb 07, 2023 9:00:49 AM org.rappsilber.fdr.gui.FDRGUI$10 run
SEVERE: null
java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "java.util.HashMap.get(Object)" is null
	at org.rappsilber.fdr.XiCSVinFDR.matchFastas(XiCSVinFDR.java:576)
	at org.rappsilber.fdr.XiCSVinFDR.readCSV(XiCSVinFDR.java:636)
	at org.rappsilber.fdr.gui.FDRGUI.addCSV(FDRGUI.java:970)
	at org.rappsilber.fdr.gui.FDRGUI.innerBatchReadCSV(FDRGUI.java:851)
	at org.rappsilber.fdr.gui.FDRGUI$10.run(FDRGUI.java:900)
	at java.base/java.lang.Thread.run(Thread.java:833)

Feb 07, 2023 9:00:49 AM org.rappsilber.gui.components.JoinedThreadedTextOuput publish
INFO: error:java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "java.util.HashMap.get(Object)" is null

Thank you for your help and time.

Also if I want to search for photoleucine and photomethionine, do I have to insert a secound modification in the fasta, like e.g L(photo) and M(photo2) or how I would do this? Because I also have to add a command like modification:known::SYMBOLEXT:photo;MODIFIED:L;DELTAMASS:11.974848 ,but it would be 8Da instead of 11Da. So do I have to add a secound command here according to M(photo2) in the fasta? 

Best wishes,
Fraenze

**Comment by lutzfischer** [comment]
My bets guess is, that it is missing some protein that is in the result list but is not in the fasta. Can you have a look if the fasta is complete?

**Comment by FraenzeMueller** [comment]
The error also apears if I start a search and run the FDR automatically afterwards. So I asume no, but I will have a deeper look into the fasta file.

**Comment by FraenzeMueller** [comment]
I found something like this as fasta header:
L(photo)ARP7_HUMAN L(photo)a-related protein 7 OS=Homo sapiens OX=9606 GN=L(photo)ARP7 PE=1 SV=1

I guess this caused the problem because there is no usual Uniprot formatting of the header anymore? Could this be the reason?

Best wishes,
Fraenze

**Comment by lutzfischer** [comment]
could be - xiFDR takes the header somewhat differntly apart then xiSEARCH - so could be that in this case they don't overlap

**Comment by lutzfischer** [comment]
It should be able to match this up - but could be that it gets confused by having more then one ARP7_HUMAN in the fasta. So not sure what is happening. Could you send me the fasta file and maybe the result and config file via email? 

A question to the photoaminoacids: are these incorporated at specific residues or random? The way here describes how to do it with sitespecific incorporation.
If you have more then one sitespecific (assuming all are Diazirine based) you would just make then you would just add each one as known modification and add all modifications as specificity for the crosslinker.

```
crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:diaz;MASS:-28.006148;FIRSTLINKEDAMINOACIDS:Lphoto,Mphoto;SECONDLINKEDAMINOACIDS:*
```

For stochastic incorporation you would rather use two crosslinker that "work" on L and M and define the mass difference of the crosslinked product to the original aminoacids.

**Comment by FraenzeMueller** [comment]
Hi Lutz,

I sent you an email to your tu-mail. Did you get this mail?

Best wishes,
