### ISSUE TITLE
CSVinFDR fails

### ISSUE THREAD

**Issue by jayieh** [Rappsilber-Laboratory/XiSearch#53]
Hi,

I am running xiSEARCH 1.7.6.1 in combo with xiFDR-2.1.2 (via GUI on a win server 2012 and java 8.0.2410).

After a successful search, I receive the following error msg:

> Sep 09, 2020 5:28:11 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: seeting up csv input
Sep 09, 2020 5:28:11 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: Read datafrom CSV
Sep 09, 2020 5:28:11 PM org.rappsilber.fdr.CSVinFDR readCSV
SEVERE: Unexecpted exception while parsing line 28
java.text.ParseException: Don't know how to handle different numbers of protein accessions and descriptions
Sep 09, 2020 5:28:11 PM rappsilber.ui.LoggingStatus setStatus
INFO: Error while running FDR
	at org.rappsilber.fdr.CSVinFDR.readCSV(CSVinFDR.java:348)
	at org.rappsilber.fdr.XiCSVinFDR.readCSV(XiCSVinFDR.java:621)
	at org.rappsilber.fdr.XiCSVinFDR.main(XiCSVinFDR.java:392)
	at org.rappsilber.fdr.CommandLine.main(CommandLine.java:49)

Sep 09, 2020 5:28:11 PM org.rappsilber.fdr.XiCSVinFDR main
SEVERE: Error while reading file: D:\juergen\200827_#20_046_ABR79-88\20200908_Xi1.7.6.1.csv

I also included the first 50 lines of the results csv

Do you have a hint on what the issue might be?

Best

Jürgen

[20200908_Xi1.7.6.1__1st_50_lines.txt](https://github.com/Rappsilber-Laboratory/XiSearch/files/5196333/20200908_Xi1.7.6.1__1st_50_lines.txt)

**Comment by andzajan** [comment]
Hi, probably this is already too late to respond, but I did encounter exactly the same issue, solution was to have Uniprot style sequence headers. Foer example:

`>sp|P08518|RPB2_nice_protein`
