### ISSUE TITLE
Strange Crashes?

### ISSUE THREAD

**Issue by MNTsnowman** [Rappsilber-Laboratory/XiSearch#60]
Hi XISearch

I am attempting to analyze my latest dataset for crosslinkers. However, XIsearch crashes every time, it generates the error below. I have tried numerous attempts with different configurations and the result is the same. If you want, you can get the config and the annotations file.

Dec 03, 2021 2:23:29 PM rappsilber.applications.SimpleXiProcessMultipleCandidates process
SEVERE: (Search_9) Error while processing spectra
java.lang.NullPointerException
        at rappsilber.ms.score.FragmentLibraryScore.score(FragmentLibraryScore.java:67)
        at rappsilber.applications.SimpleXiProcess.evaluateMatch(SimpleXiProcess.java:1860)
        at rappsilber.applications.SimpleXiProcessLinearIncluded.evaluateMatch(SimpleXiProcessLinearIncluded.java:772)
        at rappsilber.applications.SimpleXiProcessMultipleCandidates.process(SimpleXiProcessMultipleCandidates.java:518)
        at rappsilber.applications.SimpleXiProcess$SearchRunner.run(SimpleXiProcess.java:208)
        at java.lang.Thread.run(Unknown Source)

Dec 03, 2021 2:23:30 PM rappsilber.applications.SimpleXiProcessMultipleCandidates process
INFO: (Search_28)Spectra Read 64300

Dec 03, 2021 2:23:30 PM rappsilber.applications.SimpleXiProcessMultipleCandidates process
INFO: (Search_20)Spectra Read 64300

Dec 03, 2021 2:23:30 PM rappsilber.applications.SimpleXiProcessMultipleCandidates process
INFO: (Search_22)Spectra Read 64300

Dec 03, 2021 2:23:30 PM rappsilber.applications.SimpleXiProcessMultipleCandidates process
INFO: (Search_21)Spectra Read 64300

java.lang.NullPointerException
java.lang.NullPointerException
        at rappsilber.ms.score.FragmentLibraryScore.score(FragmentLibraryScore.java:67)
        at rappsilber.applications.SimpleXiProcess.evaluateMatch(SimpleXiProcess.java:1860)
        at rappsilber.applications.SimpleXiProcessLinearIncluded.evaluateMatch(SimpleXiProcessLinearIncluded.java:772)
        at rappsilber.applications.SimpleXiProcessMultipleCandidates.process(SimpleXiProcessMultipleCandidates.java:518)
        at rappsilber.applications.SimpleXiProcess$SearchRunner.run(SimpleXiProcess.java:208)
        at java.lang.Thread.run(Unknown Source)

Do you have any clue what this could be?

Kind Regards
Martin

**Comment by lutzfischer** [comment]
Can you send me a config and a minimal mgf file to test that out? Probably better to  lutz(dot)fischer tu-berlin.de  as this is might be too public.

**Comment by MNTsnowman** [comment]
Thank you, a mail has been send.
