### ISSUE TITLE
cleavable crosslinker configuration crash 1.7.6.7

### ISSUE THREAD

**Issue by grandrea** [Rappsilber-Laboratory/XiSearch#75]
Somehow, adding the lines 

    custom:loss:CleavableCrosslinkerPeptide:MASS:0;NAME:C
    loss:CleavableCrosslinkerPeptide:MASS:82.04186;NAME:S;aminoacids:K,nterm,S,T,Y

to configure my crosslinker as cleavable crashes my search with the error
```

INFO: your job will run on local system.
Dec 27, 2022 3:39:29 PM rappsilber.applications.Xi startXi
INFO: Xi Version: 1.7.6.7
Dec 27, 2022 3:39:29 PM rappsilber.ms.sequence.ions.loss.Loss parseArgs
SEVERE: null
java.lang.ClassNotFoundException: rappsilber.ms.sequence.ions.loss.CleavableCrosslinkerPeptide
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at rappsilber.ms.sequence.ions.loss.Loss.parseArgs(Loss.java:304)
	at rappsilber.config.AbstractRunConfig.evaluateConfigLine(AbstractRunConfig.java:1077)
	at rappsilber.config.RunConfigFile.ReadConfig(RunConfigFile.java:95)
	at rappsilber.applications.Xi.startXi(Xi.java:369)
	at rappsilber.applications.Xi.main(Xi.java:500)

Dec 27, 2022 3:39:29 PM rappsilber.config.RunConfigFile ReadConfig
SEVERE: Error while parsing the config-file: line 182
java.text.ParseException: CleavableCrosslinkerPeptide:MASS:0;NAME:P
	at rappsilber.ms.sequence.ions.loss.Loss.parseArgs(Loss.java:316)
	at rappsilber.config.AbstractRunConfig.evaluateConfigLine(AbstractRunConfig.java:1077)
	at rappsilber.config.RunConfigFile.ReadConfig(RunConfigFile.java:95)
	at rappsilber.applications.Xi.startXi(Xi.java:369)
	at rappsilber.applications.Xi.main(Xi.java:500)

Dec 27, 2022 3:39:29 PM rappsilber.applications.Xi main
SEVERE: ERROR: 
java.text.ParseException: Error while parsing the config-file: line: 182: loss:CleavableCrosslinkerPeptide:MASS:0;NAME:P
	at rappsilber.config.RunConfigFile.ReadConfig(RunConfigFile.java:108)
	at rappsilber.applications.Xi.startXi(Xi.java:369)
	at rappsilber.applications.Xi.main(Xi.java:500)
```

this happens with and without the "custom" in front... i can't find out where the error is. Any clues?

Thanks!

**Comment by lutzfischer** [comment]
looks like that java somehow does see all the class files. I assume you use a fairly recent version of xiSEARCH? You could try to unzip the jar file (is basicylly just a zip file) and see if the class file is there  rappsilber/ms/sequence/ions/loss/CleavableCrosslinkerPeptide.class

**Comment by grandrea** [comment]
indeed this was solved by re-downloading the software. I don't know what corrupted the .jar file i had
