### ISSUE TITLE
Unparseable number during XiFDR

### ISSUE THREAD

**Issue by aaprap** [Rappsilber-Laboratory/XiSearch#76]
Heya,

I ran .d-data (Q-TOF) through xiSearch (v2.1.5.5), which exported an CSV-file to the results-folder without any issues. 
Hereafter, I tried to run it through xiFDR (v1.7.6.7) for validation, and the first error that occurred was: 
 
```
Jan 06, 2023 14:32:18 PM org.rappsilber.data.csv.CsvParser setCurrentLine
WARNING: line 2 contains more fields than ever observed!
```

I changed the text to columns in the CSV-file (columns separated by commas) through Excel, and tried to run it in xiFDR once again. Now I've got the following message, which I can't decipher:

```
Jan 06, 2023 14:34:37 PM org.rappsilber.fdr.CSVinFDR readCSV
SEVERE: Unexecpted exception while parsing line 1
java.lang.NumberFormatException: Unparseable number: "VFGKE"
	at org.rappsilber.data.csv.CsvParser.getInteger(CsvParser.java:930)
	at org.rappsilber.fdr.CSVinFDR.readCSV(CSVinFDR.java:288)
	at org.ruappsilber.fdr.XiCSVinFDR.readCSV(XiCSVinFDR.java:634)
	at org.rappsilber.fdr.gui.FDRGUI.addCSV(FDRGUI.java:970)
	at org.rappsilber.fdr.gui.FDRGUI.innerBatchReadCSV(FDRGUI.java:851)
	at org.rappsilber.fdr.gui.FDRGUI$10.run(FDRGUI.java:900)
	at java.lang.Thread.run(Unknown Source)

Jan 06, 2023 14:34:37 PM org.rappsilber.fdr.gui.FDRGUI$10 run
SEVERE: null
java.lang.NullPointerException
	at org.rappsilber.fdr.gui.FDRGUI.setFdr(FDRGUI.java:481)
	at org.rappsilber.fdr.gui.FDRGUI$10.run(FDRGUI.java:900)
	at java.lang.Thread.run(Unknown Source)
```

May I have set the CSV-file or xiFDR up wrong, or could it be something else?

I really hit a wall here, so any help or any tips are highly appreciated.

**Comment by lars-kolbowski** [comment]
Can you provide the csv file that failed? It looks like some formatting error occurred.

**Comment by aaprap** [comment]
Certainly, it's [this one](https://github.com/Rappsilber-Laboratory/XiSearch/files/10390351/Aji24H.csv)

**Comment by aaprap** [comment]
Certainly, it's [this one](https://github.com/Rappsilber-Laboratory/XiSearch/files/10390356/Aji24H.csv)

**Comment by lutzfischer** [comment]
could you also send the file as it was before you saved it in excel?

**Comment by lutzfischer** [comment]
Next version will quote the fields that where the problem.
